apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-orderservice-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/postgres/orderservice"
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""
  claimRef:
    namespace: default
    name: postgres-orderservice-pvc
