apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
type: Opaque
data:
  POSTGRES_USER: dXNlcg==
  POSTGRES_PASSWORD_USERSERVICE: 123a
  POSTGRES_USER_ORDER: b3JkZXJ1c2Vy
  POSTGRES_PASSWORD_ORDERSERVICE: password2
  REDIS_PASSWORD: ZVlWWDdFd1ZtbXhLUEtETXdNdHlLVmdlOG9MZDJ0ODE=
